ERROR_MESSAGES={
    PROJECT_NAME_NOT_PROVIDED:'PLEASE PROVIDE PROJECT NAME',
    TECHNOLOGY_USED_NOT_PROVIDED:'PLEASE PROVIDE TECHNOLOGY USED',
    STARTING_DATE_NULL:'PLEASE PROVIDE STARTING DATE',
    COMPLETION_DATE_NULL:'PLEASE PROVIDE COMPLETION DATE'

}

FILTERVALUES={
    ALL:"all",
    COMPLETED:"completed",
    PENDING:"pending"
}

module.exports={ERROR_MESSAGES,FILTERVALUES};